-- PNU Pathfinder initial PostgreSQL schema.
-- Apply with: psql -d pnu_pathfinder -f backend/migrations/001_initial_schema.sql

CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    student_id varchar(20) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    department varchar(100) NOT NULL,
    major varchar(100),
    career_goal varchar(100),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_users_id ON users (id);
CREATE INDEX IF NOT EXISTS ix_users_student_id ON users (student_id);

CREATE TABLE IF NOT EXISTS academic_programs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department varchar(100) NOT NULL,
    major varchar(100),
    curriculum_year integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_academic_program_department_major_year UNIQUE (department, major, curriculum_year),
    CONSTRAINT ck_academic_programs_curriculum_year_min CHECK (curriculum_year >= 2000)
);

CREATE INDEX IF NOT EXISTS ix_academic_programs_id ON academic_programs (id);

CREATE TABLE IF NOT EXISTS curriculum_courses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id integer NOT NULL REFERENCES academic_programs(id) ON DELETE CASCADE,
    completion_category varchar(30) NOT NULL,
    course_number varchar(30) NOT NULL,
    course_name_ko varchar(150) NOT NULL,
    course_name_en varchar(200),
    description varchar(1000),
    recommended_semester varchar(20) NOT NULL,
    credits integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ck_curriculum_courses_credits_positive CHECK (credits > 0)
);

CREATE INDEX IF NOT EXISTS ix_curriculum_courses_id ON curriculum_courses (id);
CREATE INDEX IF NOT EXISTS ix_curriculum_courses_program_id ON curriculum_courses (program_id);

CREATE TABLE IF NOT EXISTS graduation_requirements (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id integer NOT NULL UNIQUE REFERENCES academic_programs(id) ON DELETE CASCADE,
    liberal_required integer NOT NULL,
    liberal_elective integer NOT NULL,
    major_basic integer NOT NULL,
    major_required integer NOT NULL,
    major_elective integer NOT NULL,
    general_elective integer NOT NULL,
    total_credits integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ck_graduation_requirements_liberal_required_natural CHECK (liberal_required >= 0),
    CONSTRAINT ck_graduation_requirements_liberal_elective_natural CHECK (liberal_elective >= 0),
    CONSTRAINT ck_graduation_requirements_major_basic_natural CHECK (major_basic >= 0),
    CONSTRAINT ck_graduation_requirements_major_required_natural CHECK (major_required >= 0),
    CONSTRAINT ck_graduation_requirements_major_elective_natural CHECK (major_elective >= 0),
    CONSTRAINT ck_graduation_requirements_general_elective_natural CHECK (general_elective >= 0),
    CONSTRAINT ck_graduation_requirements_total_credits_natural CHECK (total_credits >= 0)
);

CREATE INDEX IF NOT EXISTS ix_graduation_requirements_id ON graduation_requirements (id);
CREATE INDEX IF NOT EXISTS ix_graduation_requirements_program_id ON graduation_requirements (program_id);
