-- Ingestion tables for crawled or manually collected documents.
-- Apply with: psql -d pnu_pathfinder -f backend/migrations/003_ingestion_documents.sql

CREATE TABLE IF NOT EXISTS ingested_documents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_url varchar(500) NOT NULL UNIQUE,
    title varchar(200) NOT NULL,
    category varchar(50) NOT NULL DEFAULT 'notice',
    content_hash varchar(64) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_ingested_documents_id ON ingested_documents (id);
CREATE INDEX IF NOT EXISTS ix_ingested_documents_source_url ON ingested_documents (source_url);

CREATE TABLE IF NOT EXISTS document_chunks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id integer NOT NULL REFERENCES ingested_documents(id) ON DELETE CASCADE,
    chunk_index integer NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_document_chunks_document_index UNIQUE (document_id, chunk_index),
    CONSTRAINT ck_document_chunks_chunk_index_natural CHECK (chunk_index >= 0)
);

CREATE INDEX IF NOT EXISTS ix_document_chunks_id ON document_chunks (id);
CREATE INDEX IF NOT EXISTS ix_document_chunks_document_id ON document_chunks (document_id);
