-- pgvector and opportunity recommendation foundation.
-- Apply with: psql -d pnu_pathfinder -f backend/migrations/004_pgvector_and_opportunities.sql

CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE document_chunks
    ADD COLUMN IF NOT EXISTS embedding vector(1536);

CREATE TABLE IF NOT EXISTS extracurricular_programs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200) NOT NULL,
    organizer varchar(100),
    category varchar(50) NOT NULL DEFAULT 'extracurricular',
    start_date date,
    end_date date,
    application_deadline date,
    location varchar(150),
    target_department varchar(100),
    target_grade varchar(50),
    source_url varchar(500) NOT NULL UNIQUE,
    summary text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_extracurricular_programs_id ON extracurricular_programs (id);
CREATE INDEX IF NOT EXISTS ix_extracurricular_programs_source_url ON extracurricular_programs (source_url);
CREATE INDEX IF NOT EXISTS ix_extracurricular_programs_application_deadline ON extracurricular_programs (application_deadline);

CREATE TABLE IF NOT EXISTS certification_schedules (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL,
    issuer varchar(100),
    exam_date date,
    application_deadline date,
    related_career varchar(150),
    source_url varchar(500) NOT NULL UNIQUE,
    summary text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_certification_schedules_id ON certification_schedules (id);
CREATE INDEX IF NOT EXISTS ix_certification_schedules_source_url ON certification_schedules (source_url);
CREATE INDEX IF NOT EXISTS ix_certification_schedules_application_deadline ON certification_schedules (application_deadline);

CREATE TABLE IF NOT EXISTS job_opportunities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200) NOT NULL,
    organization varchar(150),
    opportunity_type varchar(50) NOT NULL DEFAULT 'job',
    application_deadline date,
    required_skills varchar(500),
    related_career varchar(150),
    source_url varchar(500) NOT NULL UNIQUE,
    summary text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_job_opportunities_id ON job_opportunities (id);
CREATE INDEX IF NOT EXISTS ix_job_opportunities_source_url ON job_opportunities (source_url);
CREATE INDEX IF NOT EXISTS ix_job_opportunities_application_deadline ON job_opportunities (application_deadline);
CREATE INDEX IF NOT EXISTS ix_job_opportunities_opportunity_type ON job_opportunities (opportunity_type);

CREATE TABLE IF NOT EXISTS lab_profiles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_name varchar(150) NOT NULL,
    professor_name varchar(100),
    department varchar(100),
    research_keywords varchar(500),
    source_url varchar(500) NOT NULL UNIQUE,
    summary text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_lab_profiles_id ON lab_profiles (id);
CREATE INDEX IF NOT EXISTS ix_lab_profiles_source_url ON lab_profiles (source_url);
CREATE INDEX IF NOT EXISTS ix_lab_profiles_department ON lab_profiles (department);
